# Generated by Django 2.0.10 on 2019-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('suspense', 'suspense'), ('crime', 'crime'), ('thriller', 'thriller'), ('tragedy', 'tragedy'), ('fiction', 'fiction')], max_length=50)),
                ('book_author', models.CharField(max_length=1000)),
            ],
        ),
    ]
